# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: Docker@2
  inputs:
    command: 'login'
    containerRegistry: 'dockerRegistryServiceConnection1'

- task: Docker@2
  inputs:
    repository: 'fanmixco/aspnetcore-docker-image'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
    command: 'logout'